/**
 * BuildingCache — serves pre-built Stockholm building footprints from a
 * static JSON file instead of hitting Overpass at runtime.
 *
 * The file public/data/stockholm-buildings.json is generated by
 * scripts/build-building-cache.py from sweden-latest.osm.pbf.
 *
 * Format: { "b": [[height, [[lat, lng], ...]], ...] }
 *
 * A simple grid index (≈500 m cells) answers radius queries in O(k) where
 * k is the number of buildings in the candidate cells — typically a few
 * hundred for a 500 m search.
 */

import type { Building } from "./SunService";

// ── Stockholm bounding box (must match the extraction bbox) ──
export const STOCKHOLM_BBOX = {
  minLat: 59.20, maxLat: 59.45,
  minLng: 17.85, maxLng: 18.25,
};

// Grid cell size — roughly 550 m × 550 m at Stockholm's latitude
const CELL_LAT = 0.005;
const CELL_LNG = 0.010;

// ── Internal state ──
let _buildings: Building[] | null = null;
let _index: Map<string, number[]> | null = null;
let _promise: Promise<void> | null = null;

function cellKey(li: number, gi: number): string {
  return `${li},${gi}`;
}
function latIdx(lat: number) { return Math.floor((lat - STOCKHOLM_BBOX.minLat) / CELL_LAT); }
function lngIdx(lng: number) { return Math.floor((lng - STOCKHOLM_BBOX.minLng) / CELL_LNG); }

async function load(): Promise<void> {
  const resp = await fetch("/data/stockholm-buildings.json");
  if (!resp.ok) throw new Error(`BuildingCache fetch failed: ${resp.status}`);
  const data: { b: [number, [number, number][]][] } = await resp.json();

  const buildings: Building[] = data.b.map(([height, polygon]) => ({
    lat: polygon[0][0],
    lng: polygon[0][1],
    height,
    polygon,
  }));

  // Build spatial grid — index each building into every cell its bbox touches
  const index = new Map<string, number[]>();
  for (let i = 0; i < buildings.length; i++) {
    const poly = buildings[i].polygon;
    let minLat = Infinity, maxLat = -Infinity, minLng = Infinity, maxLng = -Infinity;
    for (const [lat, lng] of poly) {
      if (lat < minLat) minLat = lat;
      if (lat > maxLat) maxLat = lat;
      if (lng < minLng) minLng = lng;
      if (lng > maxLng) maxLng = lng;
    }
    const liMin = latIdx(minLat), liMax = latIdx(maxLat);
    const giMin = lngIdx(minLng), giMax = lngIdx(maxLng);
    for (let li = liMin; li <= liMax; li++) {
      for (let gi = giMin; gi <= giMax; gi++) {
        const k = cellKey(li, gi);
        const bucket = index.get(k);
        if (bucket) bucket.push(i);
        else index.set(k, [i]);
      }
    }
  }

  _buildings = buildings;
  _index = index;
}

/** True when the point is inside the pre-built Stockholm coverage area. */
export function isInStockholmBbox(lat: number, lng: number): boolean {
  return (
    lat >= STOCKHOLM_BBOX.minLat && lat <= STOCKHOLM_BBOX.maxLat &&
    lng >= STOCKHOLM_BBOX.minLng && lng <= STOCKHOLM_BBOX.maxLng
  );
}

/**
 * Return all buildings whose polygon bbox touches the circle
 * (lat, lng, radiusM).  Triggers a one-time load on first call.
 */
export async function getBuildingsNear(
  lat: number,
  lng: number,
  radiusM: number
): Promise<Building[]> {
  if (!_promise) _promise = load();
  await _promise;

  const mPerDegLat = 111320;
  const mPerDegLng = 111320 * Math.cos((lat * Math.PI) / 180);
  const dLat = radiusM / mPerDegLat;
  const dLng = radiusM / mPerDegLng;

  const liMin = latIdx(lat - dLat) - 1;
  const liMax = latIdx(lat + dLat) + 1;
  const giMin = lngIdx(lng - dLng) - 1;
  const giMax = lngIdx(lng + dLng) + 1;

  const seen = new Set<number>();
  const result: Building[] = [];

  for (let li = liMin; li <= liMax; li++) {
    for (let gi = giMin; gi <= giMax; gi++) {
      const bucket = _index!.get(cellKey(li, gi));
      if (!bucket) continue;
      for (const idx of bucket) {
        if (!seen.has(idx)) {
          seen.add(idx);
          result.push(_buildings![idx]);
        }
      }
    }
  }

  return result;
}
